//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLConsole.ServiceReferenceText {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceText.IText")]
    public interface IText {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IText/UpdateText", ReplyAction="http://tempuri.org/IText/UpdateTextResponse")]
        bool UpdateText(string text, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IText/UpdateText", ReplyAction="http://tempuri.org/IText/UpdateTextResponse")]
        System.Threading.Tasks.Task<bool> UpdateTextAsync(string text, int idUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITextChannel : KLConsole.ServiceReferenceText.IText, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextClient : System.ServiceModel.ClientBase<KLConsole.ServiceReferenceText.IText>, KLConsole.ServiceReferenceText.IText {
        
        public TextClient() {
        }
        
        public TextClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateText(string text, int idUser) {
            return base.Channel.UpdateText(text, idUser);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTextAsync(string text, int idUser) {
            return base.Channel.UpdateTextAsync(text, idUser);
        }
    }
}
