//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLConsole.ServiceReferenceSystem {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSystem.ISystem")]
    public interface ISystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSysInfo", ReplyAction="http://tempuri.org/ISystem/AddSysInfoResponse")]
        bool AddSysInfo(string os, string pcName, string processoeInfo, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSysInfo", ReplyAction="http://tempuri.org/ISystem/AddSysInfoResponse")]
        System.Threading.Tasks.Task<bool> AddSysInfoAsync(string os, string pcName, string processoeInfo, int idUser);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemChannel : KLConsole.ServiceReferenceSystem.ISystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemClient : System.ServiceModel.ClientBase<KLConsole.ServiceReferenceSystem.ISystem>, KLConsole.ServiceReferenceSystem.ISystem {
        
        public SystemClient() {
        }
        
        public SystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddSysInfo(string os, string pcName, string processoeInfo, int idUser) {
            return base.Channel.AddSysInfo(os, pcName, processoeInfo, idUser);
        }
        
        public System.Threading.Tasks.Task<bool> AddSysInfoAsync(string os, string pcName, string processoeInfo, int idUser) {
            return base.Channel.AddSysInfoAsync(os, pcName, processoeInfo, idUser);
        }
    }
}
